### ISSUE TITLE
`playwright-extra` npm package

### ISSUE THREAD

**Issue by berstend** [shirshak55/playwright-mini#1]
Hi @shirshak55 👋 

I'm the maintainer of `puppeteer-extra` and the `stealth` plugin - I've been working on a [massive rewrite](https://github.com/berstend/puppeteer-extra/pull/303) for a few months now to support playwright as well - with the documented intent of publishing the playwright port as `playwright-extra`.

I appreciate that you worked on improving the ecosystem as well:
https://www.npmjs.com/package/playwright-extra

Unfortunately the naming you chose clashes with our existing project and intent to publish the playwright port under this very name.

Given that you just published this package **can you choose a different package name** and [transfer package ownership](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) over to [me](https://www.npmjs.com/~berstend)? :-)

I was thinking about pushing a placeholder package a couple of months back, but assumed no one would use this package name lol.

Thanks a lot!

**Comment by shirshak55** [comment]
Hi @berstend  . Nice to meet you :)

Sorry for squatting package unintentionally :(. Initially I thought not to use the name. But nobody used the name and I thought you were not interested in making port for playwright and you might be committing to puppeteer  I decided to make simple version of playwright-extra to puppeteer.

But I realized this name is important to you so I will transfer it to your name soon (Within 1-2 day just to make sure none of my existing project is using playwright-extra code).

I have already starting working in it . Rest be assured the package name will yours :)


Thank You!!

**Comment by berstend** [comment]
@shirshak55 awesome - thanks a lot for being nice and understanding, much appreciated 😊👍 

In regards to Puppeteer vs Playwright:
I think both of them have pros & cons, that's why I want to have a single plugin framework for both (they're quite similar so it's technically possible).

I saw in the readme that you're not a huge fan of how `puppeteer-extra` handles modularity and evasion plugins: I'm working on a more elegant way to pass a single set of options to the stealth plugin, so it becomes less apparent that behind the scenes the stealth plugin is just a collection of standalone plugins as well. :-)

Also nice to e-meet and thanks again for your fast and much appreciated response! 💯

**Comment by shirshak55** [comment]
@berstend 

Regarding Puppeteer I have am not being incorrect its already dead. Issue like this https://github.com/puppeteer/puppeteer/issues/1342 has just become headache to me and there are many unreported issue I have faced like response not working properly and most of time I need to go path to CDP just to accomplish simple thing like download etc.  However I acknowledge there are lot of package that depends on puppeteer so its fair enough to support it from you side :)


And that's good to hear you are solving the stealth issue and modular related issue :) Lets see if its ergonomic i can remove this playwright mini :)

And I hope 1-2 day is not too much for you. I am working on changing all playwright-extra for playwright-mini so that you can use the name 👍🏼 

Thanks you and sorry for creating problem to you that you have to spend time on such issue :)

**Comment by berstend** [comment]
The package transfer was successful, thanks again @shirshak55 💪 

https://www.npmjs.com/package/playwright-extra
